export { default as Home } from './Home';
export { default as SignUp } from './SignUp';
export { default as SignIn } from './SignIn';
export { default as Board } from './Board';
export { default as BoardDetail } from './BoardDetail';
export { default as BoardWrite } from './BoardWrite';
export { default as MyInfo } from './MyInfo';
export { default as SocialLogin } from './SocialLogin';
export { default as InstallmentSaving } from './InstallmentSaving';